databases:
  - name: lab3-4-db-qlta-v2
    plan: free
    region: frankfurt

services:
  - type: web
    name: lab3-4-flask-qlta
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "flask db upgrade && gunicorn -w 1 app:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lab3-4-db-qlta-v2
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.13.4